# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-08-22 07:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Кафедра')),
            ],
            options={
                'verbose_name_plural': 'Кафедры',
                'ordering': ['title'],
                'verbose_name': 'Кафедра',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Город')),
                ('area', models.CharField(blank=True, default='', max_length=200, verbose_name='Область')),
                ('region_text', models.CharField(blank=True, default='', max_length=200, verbose_name='Регион')),
            ],
            options={
                'verbose_name_plural': 'Города',
                'ordering': ['title'],
                'verbose_name': 'Город',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('data', models.CharField(default='', max_length=200, verbose_name='Набор данных')),
                ('order', models.IntegerField(default=0, verbose_name='Позиция')),
                ('orderable', models.BooleanField(default=True, verbose_name='Сортируемый')),
                ('fixed', models.BooleanField(default=False, verbose_name='Зафиксировать')),
                ('hide', models.BooleanField(default=False, verbose_name='Не скрываемый')),
                ('searchable', models.BooleanField(default=True, verbose_name='Поиск по столбщу')),
                ('visible', models.BooleanField(default=True, verbose_name='Отображаемый (по умолчанию)')),
            ],
            options={
                'verbose_name_plural': 'Столбцы',
                'ordering': ['table', 'order'],
                'verbose_name': 'Столбец',
            },
        ),
        migrations.CreateModel(
            name='ControlUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(default='', max_length=200, verbose_name='Фамилия')),
                ('firstName', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('patronymic', models.CharField(default='', max_length=200, verbose_name='Отчество')),
                ('updatedAt', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего обновления')),
                ('removeAt', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['lastName', 'firstName'],
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Страны',
                'ordering': ['title'],
                'verbose_name': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Факультет')),
            ],
            options={
                'verbose_name_plural': 'Факультеты',
                'ordering': ['title'],
                'verbose_name': 'Факультет',
            },
        ),
        migrations.CreateModel(
            name='LastUpdateConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200, verbose_name='Тип')),
                ('dateStart', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата начала')),
                ('dateEnd', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name_plural': 'Последние обновления конфигурации',
                'ordering': ['type'],
                'verbose_name': 'Последнее обновление конфигурации',
            },
        ),
        migrations.CreateModel(
            name='MetroStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Метро')),
                ('color', models.CharField(default='', max_length=200, verbose_name='Метро')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Станции метро',
                'ordering': ['name'],
                'verbose_name': 'Станция метро',
            },
        ),
        migrations.CreateModel(
            name='PatternColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.Column', verbose_name='Столбец')),
            ],
            options={
                'verbose_name_plural': 'Шаблоны Столбцы',
                'verbose_name': 'Шаблон Столбец',
            },
        ),
        migrations.CreateModel(
            name='PatternTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Шаблоны',
                'ordering': ['name'],
                'verbose_name': 'Шаблон',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Регион')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Countries', verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
                'ordering': ['title'],
                'verbose_name': 'Регион',
            },
        ),
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200, verbose_name='Тип')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Рендеры',
                'ordering': ['name'],
                'verbose_name': 'Рендер',
            },
        ),
        migrations.CreateModel(
            name='SchoolClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Школьные классы')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Countries', verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'Школьные классы',
                'ordering': ['title'],
                'verbose_name': 'Школьный класс',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Школа')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Cities', verbose_name='Город')),
            ],
            options={
                'verbose_name_plural': 'Школы',
                'ordering': ['title'],
                'verbose_name': 'Школа',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200, unique=True, verbose_name='Тип')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Таблицы',
                'ordering': ['name'],
                'verbose_name': 'Таблица',
            },
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(verbose_name='ВК id')),
                ('title', models.CharField(default='', max_length=200, verbose_name='ВУЗ')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Cities', verbose_name='Город')),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Countries', verbose_name='Страна')),
            ],
            options={
                'verbose_name_plural': 'ВУЗы',
                'ordering': ['title'],
                'verbose_name': 'ВУЗ',
            },
        ),
        migrations.AddField(
            model_name='patterntable',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.Table', verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='patterncolumn',
            name='pattern',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.PatternTable', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='faculties',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Universities', verbose_name='ВУЗ'),
        ),
        migrations.AddField(
            model_name='column',
            name='render',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Render', verbose_name='Рендер'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Site.Table', verbose_name='Таблица'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Countries', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='cities',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Regions', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='chairs',
            name='faculties',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Faculties', verbose_name='Факультет'),
        ),
    ]
