# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-08-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controluser',
            name='birthDate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
    ]
