# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-08-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_auto_20220822_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlUserImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.ControlUser')),
            ],
            options={
                'verbose_name_plural': 'Фото сотрудников',
                'verbose_name': 'Фото сотрудника',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='Site/uploads/', verbose_name='Файл')),
            ],
            options={
                'verbose_name_plural': 'Название',
                'ordering': ['name'],
                'verbose_name': 'Название',
            },
        ),
        migrations.AddField(
            model_name='controluserimg',
            name='file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.File'),
        ),
    ]
