# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-08-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20220823_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name'], 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='controluserimg',
            name='removeAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='file',
            name='removeAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
    ]
