# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-09-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_auto_20220829_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=200, verbose_name='Значение')),
                ('removeAt', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('controlUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.ControlUser')),
            ],
            options={
                'verbose_name_plural': 'Номера телефонов',
                'ordering': ['value'],
                'verbose_name': 'Номер телефона',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=200, verbose_name='Значение')),
                ('removeAt', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления')),
                ('controlUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.ControlUser')),
            ],
            options={
                'verbose_name_plural': 'Номера телефонов',
                'ordering': ['value'],
                'verbose_name': 'Номер телефона',
            },
        ),
    ]
