# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-09-26 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_mail_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlUserPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.ControlUser')),
            ],
            options={
                'verbose_name_plural': 'Фото сотрудников',
                'verbose_name': 'Фото сотрудника',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Cities', verbose_name='Город')),
            ],
            options={
                'ordering': ['country', 'region', 'city'],
                'verbose_name_plural': 'Места',
                'verbose_name': 'Место',
            },
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'ordering': ['value'], 'verbose_name': 'Адрес эл.почты', 'verbose_name_plural': 'Адреса эл.почт'},
        ),
        migrations.RemoveField(
            model_name='countries',
            name='vid',
        ),
        migrations.AddField(
            model_name='countries',
            name='removeAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='place',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Countries', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Regions', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='controluserplace',
            name='place',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Place', verbose_name='Место'),
        ),
    ]
