# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-09-26 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_auto_20220926_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='removeAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='regions',
            name='removeAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
    ]
