# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-09-26 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_auto_20220926_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regions',
            name='vid',
        ),
    ]
