# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-09-29 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_remove_regions_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='area',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='region_text',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='vid',
        ),
    ]
