# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_auto_20220929_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=200, verbose_name='Номер ВЧ')),
            ],
            options={
                'verbose_name_plural': 'Воинские части',
                'verbose_name': 'Воинская часть',
                'ordering': ['number'],
            },
        ),
        migrations.RemoveField(
            model_name='metrostations',
            name='city',
        ),
        migrations.RemoveField(
            model_name='chairs',
            name='vid',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='vid',
        ),
        migrations.RemoveField(
            model_name='schoolclasses',
            name='vid',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='vid',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='vid',
        ),
        migrations.DeleteModel(
            name='MetroStations',
        ),
    ]
