# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20221003_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='vch',
            name='removeAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
    ]
