# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-04 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0013_vch_removeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairs',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='faculties',
            name='university',
        ),
        migrations.RemoveField(
            model_name='schoolclasses',
            name='country',
        ),
        migrations.DeleteModel(
            name='Chairs',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='SchoolClasses',
        ),
    ]
