# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-04 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_auto_20221004_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universities',
            name='country',
        ),
    ]
