# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-10 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0017_auto_20221007_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='city',
        ),
        migrations.RemoveField(
            model_name='universities',
            name='city',
        ),
        migrations.DeleteModel(
            name='Schools',
        ),
        migrations.DeleteModel(
            name='Universities',
        ),
    ]
