# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0018_auto_20221010_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='controluser',
            name='schools',
            field=models.TextField(default='', verbose_name='Школа'),
        ),
        migrations.AddField(
            model_name='controluser',
            name='universities',
            field=models.TextField(default='', verbose_name='ВУЗ'),
        ),
    ]
