# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-10 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0020_auto_20221010_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controluser',
            name='vch',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Vch', verbose_name='Место военной службы'),
        ),
    ]
