# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-10 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0021_auto_20221010_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='searchable',
        ),
    ]
