# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_remove_column_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='searchable',
            field=models.BooleanField(default=False, verbose_name='Поиск по столбщу'),
        ),
    ]
