# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0024_remove_column_searchable'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='view',
            field=models.BooleanField(default=True, verbose_name='Отображаемый в карточке'),
        ),
        migrations.AddField(
            model_name='column',
            name='viewOrder',
            field=models.IntegerField(default=0, verbose_name='Позиция в карточке'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='birthDay',
            field=models.IntegerField(blank=True, default=0, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='birthMonth',
            field=models.IntegerField(blank=True, default=0, verbose_name='Месяц рождения'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='birthYear',
            field=models.IntegerField(blank=True, default=0, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='schools',
            field=models.TextField(blank=True, default='', verbose_name='Школа'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='universities',
            field=models.TextField(blank=True, default='', verbose_name='ВУЗ'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='work',
            field=models.TextField(blank=True, default='', verbose_name='Место работы'),
        ),
    ]
