# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0025_auto_20221011_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200, unique=True, verbose_name='Тип')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Статусы',
                'verbose_name': 'Статусы',
                'ordering': ['name'],
            },
        ),
    ]
