# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0026_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['value', 'name'], 'verbose_name': 'Статусы', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='status',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
    ]
