# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0027_auto_20221011_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='controluser',
            name='firstNameT',
            field=models.CharField(default='', max_length=200, verbose_name='Имя (транслит)'),
        ),
        migrations.AddField(
            model_name='controluser',
            name='lastNameT',
            field=models.CharField(default='', max_length=200, verbose_name='Фамилия (транслит)'),
        ),
        migrations.AddField(
            model_name='controluser',
            name='patronymicT',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Отчество (транслит)'),
        ),
    ]
