# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0028_auto_20221012_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=200, unique=True, verbose_name='Тип')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Название')),
                ('value', models.IntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Этап статуса',
                'ordering': ['value', 'name'],
                'verbose_name_plural': 'Этапы статусов',
            },
        ),
        migrations.AlterModelOptions(
            name='controluser',
            options={'ordering': ['lastName', 'firstName', 'patronymic'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['stage', 'value', 'name'], 'verbose_name': 'Статусы', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='status',
            name='stage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.StatusStage', verbose_name='Этап'),
        ),
    ]
