# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-12 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0029_auto_20221012_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='controluser',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Status', verbose_name='Место военной службы'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='firstNameT',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя (транслит)'),
        ),
        migrations.AlterField(
            model_name='controluser',
            name='lastNameT',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Фамилия (транслит)'),
        ),
    ]
