# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0030_auto_20221012_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controluser',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.Status', verbose_name='Статус'),
        ),
    ]
