# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-12 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0031_auto_20221012_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='', max_length=200, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение (%)'),
        ),
    ]
