# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-12 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0032_auto_20221012_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=200, verbose_name='Значение')),
                ('controlUser', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.ControlUser')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'ordering': ['value'],
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
