# Generated by Django 3.2.16 on 2022-10-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0033_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorruptType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Значение')),
                ('orderBy', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Тип данных',
                'verbose_name_plural': 'Типы данных',
                'ordering': ['orderBy', 'title', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CorruptInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=200, verbose_name='Значение')),
                ('info', models.TextField(blank=True, default='', verbose_name='Информация')),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.corrupttype', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
                'ordering': ['value', 'pk'],
            },
        ),
    ]
