# Generated by Django 3.2.16 on 2022-10-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0034_corruptinfo_corrupttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptinfo',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.corrupttype', verbose_name='Типы данных'),
        ),
    ]
