# Generated by Django 3.2.16 on 2022-10-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0035_alter_corruptinfo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corruptinfo',
            name='type',
        ),
        migrations.AddField(
            model_name='corruptinfo',
            name='removeAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата удаления'),
        ),
        migrations.DeleteModel(
            name='CorruptType',
        ),
    ]
