# Generated by Django 3.2.16 on 2022-10-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0036_auto_20221017_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField(default=0, verbose_name='Номер поста')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата добавления')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст поста')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
