# Generated by Django 3.2.16 on 2022-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0037_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_post',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер поста'),
        ),
    ]
