# Generated by Django 3.2.16 on 2022-10-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0038_alter_post_id_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField(blank=True, default=0, verbose_name='Номер видеозаписи')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата добавления')),
                ('name', models.TextField(blank=True, default='', verbose_name='Название видеозаписи')),
                ('link', models.TextField(blank=True, default='', verbose_name='Ссылка на видеозапись')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Видеозапись',
                'verbose_name_plural': 'Видеозаписи',
            },
        ),
    ]
