# Generated by Django 3.2.16 on 2022-10-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0040_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(blank=True, default=0, verbose_name='Номер пользователя')),
                ('about', models.TextField(blank=True, default='', verbose_name='О себе')),
                ('activities', models.TextField(blank=True, default='', verbose_name='Деятельность')),
                ('books', models.TextField(blank=True, default='', verbose_name='Любимые книги')),
                ('games', models.TextField(blank=True, default='', verbose_name='Любимые игры')),
                ('interests', models.TextField(blank=True, default='', verbose_name='Интересы')),
                ('movies', models.TextField(blank=True, default='', verbose_name='Любимые фильмы')),
                ('music', models.TextField(blank=True, default='', verbose_name='Любимая музыка')),
                ('nickname', models.TextField(blank=True, default='', verbose_name='Никнейм')),
                ('quotes', models.TextField(blank=True, default='', verbose_name='Любимые цитаты')),
                ('status', models.TextField(blank=True, default='', verbose_name='Статус пользователя')),
                ('tv', models.TextField(blank=True, default='', verbose_name='Любимые телешоу')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
                'verbose_name_plural': 'Информация о пользователях',
            },
        ),
    ]
