# Generated by Django 3.2.16 on 2022-10-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0041_inf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(blank=True, default=0, verbose_name='Номер пользователя')),
                ('link', models.TextField(blank=True, default='', verbose_name='Ссылка на фотоизображение')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Фотоизображение',
                'verbose_name_plural': 'Фотоизображения',
            },
        ),
    ]
