# Generated by Django 3.2.16 on 2022-10-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0042_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inf',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='id_user',
        ),
        migrations.CreateModel(
            name='VideoChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_video', models.IntegerField(blank=True, default=0, verbose_name='Номер видеозаписи')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Проверенная видеозапись',
                'verbose_name_plural': 'Проверенные видеозаписи',
            },
        ),
        migrations.CreateModel(
            name='PostsChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField(blank=True, default=0, verbose_name='Номер поста')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Проверенный пост',
                'verbose_name_plural': 'Проверенные посты',
            },
        ),
        migrations.CreateModel(
            name='PhotosChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, default='', verbose_name='Ссылка на фотоизображение')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Проверенное фотоизображение',
                'verbose_name_plural': 'Проверенные фотоизображения',
            },
        ),
        migrations.CreateModel(
            name='InfChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, default='', verbose_name='О себе')),
                ('activities', models.TextField(blank=True, default='', verbose_name='Деятельность')),
                ('books', models.TextField(blank=True, default='', verbose_name='Любимые книги')),
                ('games', models.TextField(blank=True, default='', verbose_name='Любимые игры')),
                ('interests', models.TextField(blank=True, default='', verbose_name='Интересы')),
                ('movies', models.TextField(blank=True, default='', verbose_name='Любимые фильмы')),
                ('music', models.TextField(blank=True, default='', verbose_name='Любимая музыка')),
                ('nickname', models.TextField(blank=True, default='', verbose_name='Никнейм')),
                ('quotes', models.TextField(blank=True, default='', verbose_name='Любимые цитаты')),
                ('status', models.TextField(blank=True, default='', verbose_name='Статус пользователя')),
                ('tv', models.TextField(blank=True, default='', verbose_name='Любимые телешоу')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Проверенная информация о пользователе',
                'verbose_name_plural': 'Проверенная информация о пользователях',
            },
        ),
        migrations.CreateModel(
            name='GroupsChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_groups', models.IntegerField(blank=True, default=0, verbose_name='Номер сообщества')),
                ('social', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Site.social')),
            ],
            options={
                'verbose_name': 'Проверенное сообщество',
                'verbose_name_plural': 'Проверенные сообщества',
            },
        ),
    ]
