# Generated by Django 3.2.16 on 2022-10-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0043_auto_20221018_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfChecks',
        ),
    ]
