# Generated by Django 3.2.16 on 2022-10-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0044_delete_infchecks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(default='', max_length=200, verbose_name='Тип'),
        ),
    ]
