# Generated by Django 3.2.16 on 2022-10-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0045_alter_status_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
    ]
