# Generated by Django 3.2.16 on 2022-10-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0046_social_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='social',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
    ]
