# Generated by Django 3.2.16 on 2022-10-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0048_social_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='prefix',
            field=models.CharField(default='https://vk.com/id', max_length=200, verbose_name='Префикс'),
        ),
    ]
