# Generated by Django 3.2.16 on 2022-10-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0050_allusersvk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusersvk',
            name='bdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
    ]
