# Generated by Django 3.2.16 on 2022-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0051_alter_allusersvk_bdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusersvk',
            name='bdate',
            field=models.TextField(blank=True, default='', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='allusersvk',
            name='id_user',
            field=models.IntegerField(blank=True, default=0, verbose_name='id пользователя'),
        ),
    ]
