# Generated by Django 3.2.16 on 2022-10-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0052_auto_20221020_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='degree_violation',
            field=models.TextField(blank=True, default='', verbose_name='Степень нарушения'),
        ),
        migrations.AddField(
            model_name='inf',
            name='degree_violation',
            field=models.TextField(blank=True, default='', verbose_name='Степень нарушения'),
        ),
        migrations.AddField(
            model_name='photos',
            name='degree_violation',
            field=models.TextField(blank=True, default='', verbose_name='Степень нарушения'),
        ),
        migrations.AddField(
            model_name='post',
            name='degree_violation',
            field=models.TextField(blank=True, default='', verbose_name='Степень нарушения'),
        ),
        migrations.AddField(
            model_name='video',
            name='degree_violation',
            field=models.TextField(blank=True, default='', verbose_name='Степень нарушения'),
        ),
    ]
