# Generated by Django 3.2.16 on 2022-10-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0052_auto_20221020_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
