# Generated by Django 3.2.16 on 2022-10-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0053_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='Site/uploads/', verbose_name='Файл'),
        ),
    ]
