# Generated by Django 3.2.16 on 2022-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0054_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
    ]
