# Generated by Django 3.2.16 on 2022-10-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0054_alter_corruptinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenVK', models.TextField(blank=True, default='', verbose_name='Токен администратора')),
            ],
            options={
                'verbose_name': 'Токен администратора',
                'verbose_name_plural': 'Токены администратора',
            },
        ),
    ]
