# Generated by Django 3.2.16 on 2022-10-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0055_tokenadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokensForVkUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenVK', models.TextField(blank=True, default='', verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Токен для обновления базы пользователей VK',
                'verbose_name_plural': 'Токены для обновления базы пользователей VK',
            },
        ),
    ]
