# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-21 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0057_auto_20221020_1835'),
        ('Site', '0056_tokensforvkupdate'),
    ]

    operations = [
    ]
