# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0058_merge_20221021_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
