# Generated by Django 3.2.16 on 2022-10-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0059_auto_20221021_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='degree_violation',
        ),
        migrations.RemoveField(
            model_name='inf',
            name='degree_violation',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='degree_violation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='degree_violation',
        ),
        migrations.RemoveField(
            model_name='video',
            name='degree_violation',
        ),
    ]
