# Generated by Django 3.2.16 on 2022-10-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0061_groupscorrupt_infcorrupt_photoscorrupt_postcorrupt_videocorrupt'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='inf',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='photos',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='post',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='video',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
    ]
