# Generated by Django 3.2.16 on 2022-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0062_auto_20221025_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='confirmedAt',
        ),
        migrations.RemoveField(
            model_name='inf',
            name='confirmedAt',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='confirmedAt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='confirmedAt',
        ),
        migrations.RemoveField(
            model_name='video',
            name='confirmedAt',
        ),
        migrations.AddField(
            model_name='groupscorrupt',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='infcorrupt',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='photoscorrupt',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='postcorrupt',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AddField(
            model_name='videocorrupt',
            name='confirmedAt',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
    ]
