# Generated by Django 3.2.16 on 2022-10-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0063_auto_20221026_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='searchable',
            field=models.BooleanField(default=True, verbose_name='Поиск в столбце'),
        ),
    ]
