# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-31 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0064_column_searchable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default='', max_length=200)),
                ('value', models.TextField(default='')),
            ],
            options={
                'ordering': ['key', 'pk'],
            },
        ),
    ]
