# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-31 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0065_environments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environments',
            name='key',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True),
        ),
    ]
