# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-31 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0066_auto_20221031_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptinfo',
            name='value',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Значение'),
        ),
    ]
