# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-31 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0068_corruptinfo_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptinfo',
            name='tech',
            field=models.BooleanField(default=True, verbose_name='Управление администратором'),
        ),
    ]
