# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2022-10-31 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0069_auto_20221031_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corruptinfo',
            name='tech',
            field=models.BooleanField(default=False, verbose_name='Управление администратором'),
        ),
        migrations.AlterField(
            model_name='table',
            name='type',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True, verbose_name='Тип'),
        ),
    ]
